"""create external identities table

Revision ID: 0634baca95f1
Revises: 6d5a50026115
Create Date: 2026-08-25 09:39:33.527747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0634baca95f1'
down_revision: Union[str, Sequence[str], None] = '6d5a50026115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identidades_externas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('provedor', sa.String(), nullable=False),
    sa.Column('identificador_externo', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provedor', 'identificador_externo', name='uq_identidade_provedor_identificador')
    )
    op.create_index(op.f('ix_identidades_externas_id'), 'identidades_externas', ['id'], unique=False)
    op.add_column('usuarios', sa.Column('nome', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('ativo', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('criado_em', sa.DateTime(), nullable=True))

    op.execute(
    """
    UPDATE usuarios
    SET
        nome = COALESCE(nome, 'Neto'),
        ativo = COALESCE(ativo, TRUE),
        criado_em = COALESCE(criado_em, CURRENT_TIMESTAMP)
    """
    )

    op.alter_column(
    "usuarios",
    "nome",
    existing_type=sa.String(),
    nullable=False
    )

    op.alter_column(
        "usuarios",
        "ativo",
        existing_type=sa.Boolean(),
        nullable=False
    )

    op.alter_column(
        "usuarios",
        "criado_em",
        existing_type=sa.DateTime(),
        nullable=False
    )
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'criado_em')
    op.drop_column('usuarios', 'ativo')
    op.drop_column('usuarios', 'nome')
    op.drop_index(op.f('ix_identidades_externas_id'), table_name='identidades_externas')
    op.drop_table('identidades_externas')
    # ### end Alembic commands ###
