"""add external reference to finances

Revision ID: a1e164e8b31f
Revises: c6ab6a9ab7f7
Create Date: 2026-08-26 14:18:08.654129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e164e8b31f'
down_revision: Union[str, Sequence[str], None] = 'c6ab6a9ab7f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financas', sa.Column('referencia_externa', sa.String(), nullable=True))
    op.create_index(op.f('ix_financas_referencia_externa'), 'financas', ['referencia_externa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financas_referencia_externa'), table_name='financas')
    op.drop_column('financas', 'referencia_externa')
    # ### end Alembic commands ###
