"""associate Minhas Economias tokens with user

Revision ID: a3ec54e3c3b1
Revises: ea2006cb8450
Create Date: 2026-09-08 15:47:21.977690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ec54e3c3b1'
down_revision: Union[str, Sequence[str], None] = 'ea2006cb8450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minhas_economias_token', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.execute(
    """
    UPDATE minhas_economias_token
    SET usuario_id = 1
    WHERE usuario = 'usuario_local'
    """
    )
    op.alter_column(
    "minhas_economias_token",
    "usuario_id",
    existing_type=sa.Integer(),
    nullable=False,
    )
    op.drop_index(op.f('ix_minhas_economias_token_usuario'), table_name='minhas_economias_token')
    op.create_index(op.f('ix_minhas_economias_token_usuario_id'), 'minhas_economias_token', ['usuario_id'], unique=True)
    op.create_foreign_key(
            "fk_minhas_economias_token_usuario_id_usuarios",
            "minhas_economias_token",
            "usuarios",
            ["usuario_id"],
            ["id"],
        )
    op.drop_column("minhas_economias_token", "usuario")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minhas_economias_token', sa.Column('usuario', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute(
        """
        UPDATE minhas_economias_token
        SET usuario = CASE
            WHEN usuario_id = 1 THEN 'usuario_local'
            ELSE 'usuario_' || usuario_id::text
        END
        """
    )
    op.alter_column(
        "minhas_economias_token",
        "usuario",
        existing_type=sa.String(),
        nullable=False,
    )
    op.drop_constraint(
        "fk_minhas_economias_token_usuario_id_usuarios",
        "minhas_economias_token",
        type_="foreignkey",
    )
    op.drop_index(op.f('ix_minhas_economias_token_usuario_id'), table_name='minhas_economias_token')
    op.create_index(op.f('ix_minhas_economias_token_usuario'), 'minhas_economias_token', ['usuario'], unique=True)
    op.drop_column('minhas_economias_token', 'usuario_id')
    # ### end Alembic commands ###
