"""add owner to finances

Revision ID: c6ab6a9ab7f7
Revises: 0634baca95f1
Create Date: 2026-08-25 11:19:35.369572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ab6a9ab7f7'
down_revision: Union[str, Sequence[str], None] = '0634baca95f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financas', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.execute(
    """
    UPDATE financas
    SET usuario_id = 1
    WHERE usuario_id IS NULL
    """
    )
    op.alter_column(
    "financas",
    "usuario_id",
    existing_type=sa.Integer(),
    nullable=False
    )
    op.create_index(op.f('ix_financas_usuario_id'), 'financas', ['usuario_id'], unique=False)
    op.create_foreign_key('fk_financas_usuario_id_usuarios', 'financas', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_financas_usuario_id_usuarios', 'financas', type_='foreignkey')
    op.drop_index(op.f('ix_financas_usuario_id'), table_name='financas')
    op.drop_column('financas', 'usuario_id')
    # ### end Alembic commands ###
