"""create user integrations

Revision ID: dee1cbe97c45
Revises: a3ec54e3c3b1
Create Date: 2026-09-22 15:19:55.217009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee1cbe97c45'
down_revision: Union[str, Sequence[str], None] = 'a3ec54e3c3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integracoes_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('provedor', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'provedor', name='uq_integracao_usuario_provedor')
    )
    op.create_index(op.f('ix_integracoes_usuario_id'), 'integracoes_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_integracoes_usuario_usuario_id'), 'integracoes_usuario', ['usuario_id'], unique=False)
    op.create_index('uq_integracao_principal_por_usuario', 'integracoes_usuario', ['usuario_id'], unique=True, postgresql_where=sa.text('principal = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_integracao_principal_por_usuario', table_name='integracoes_usuario', postgresql_where=sa.text('principal = true'))
    op.drop_index(op.f('ix_integracoes_usuario_usuario_id'), table_name='integracoes_usuario')
    op.drop_index(op.f('ix_integracoes_usuario_id'), table_name='integracoes_usuario')
    op.drop_table('integracoes_usuario')
    # ### end Alembic commands ###
