"""add per user transaction number

Revision ID: ea2006cb8450
Revises: a1e164e8b31f
Create Date: 2026-08-27 14:24:01.003275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2006cb8450'
down_revision: Union[str, Sequence[str], None] = 'a1e164e8b31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financas', sa.Column('numero_usuario', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('proximo_numero_transacao', sa.Integer(), nullable=True))
    op.execute(
    """
    WITH transacoes_numeradas AS (
        SELECT
            id,
            ROW_NUMBER() OVER (
                PARTITION BY usuario_id
                ORDER BY data, id
            ) AS numero
        FROM financas
    )
    UPDATE financas
    SET numero_usuario = transacoes_numeradas.numero
    FROM transacoes_numeradas
    WHERE financas.id = transacoes_numeradas.id
    """
    )

    op.execute(
    """
    UPDATE usuarios
    SET proximo_numero_transacao = COALESCE(
        (
            SELECT MAX(financas.numero_usuario) + 1
            FROM financas
            WHERE financas.usuario_id = usuarios.id
        ),
        1
    )
    """
    )
    op.alter_column(
    "financas",
    "numero_usuario",
    existing_type=sa.Integer(),
    nullable=False,
)

    op.alter_column(
        "usuarios",
        "proximo_numero_transacao",
        existing_type=sa.Integer(),
        nullable=False,
    )
    op.create_unique_constraint('uq_financa_usuario_numero', 'financas', ['usuario_id', 'numero_usuario'])
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'proximo_numero_transacao')
    op.drop_constraint('uq_financa_usuario_numero', 'financas', type_='unique')
    op.drop_column('financas', 'numero_usuario')
    # ### end Alembic commands ###
